### ISSUE TITLE
[iPad] Add > Observinglist doesn't work.

### ISSUE THREAD

**Issue by svdwal** [DeepskyLog/DeepskyLog#707] opened 2018-04-18 05:27 UTC
The menu drops down fine, but pressing on Observing list results in nothing happening. Pressing other menu entries, like Observations, Session or Instrument, work fine.

**Comment by WimDeMeester** [comment] 2018-05-03 08:50
It is difficult to test for me, because I don't have an iPad... I can however set Safari on my Mac to behave as an iPad, and when I click, I see this: 
![image](https://user-images.githubusercontent.com/7261529/39567602-cf0333e8-4ebf-11e8-98fe-9d25545adc1c.png)

**Comment by svdwal** [comment] 2018-06-06 15:58
That button does work, and I see the same dialog. 

What I do not understand is that a menu entry does not work. It appears that menu entry points to the wrong function. Could be just some typo in the menu definition.

**Comment by WimDeMeester** [comment] 2018-06-07 08:43
I don't understand what the problem is... So, you see the dialog and what is the problem then?

**Comment by svdwal** [comment] 2018-09-12 19:38
It looks like it is working now. I can see the dialog, press on "Maak lijst aan" and the list is created. If I press "Close" the dialog is dismissed without a new list. That's all good.

One tiny issue though, which is really a different bug. Moving the mouse pointer over the menu entries highlights them. When the cursor is over "Waarneemlijst" it is a caret. Over every other menu entry it is a pointing hand. No screenshots as the mouse pointer is not in the screenshot.

Carets are commonly used in text entry fields, AFAIK

**Comment by WimDeMeester** [comment] 2020-02-19 18:44
The observing lists will be totally rewritten for the laravel version of DeepskyLog. Closing this ticket as I will not solve this for the current version of DeepskyLog.

**Closed by WimDeMeester** 2020-02-19 18:44 UTC
Labels: Deepsky, Laravel, bug
