### ISSUE TITLE
RRO function doesn't seem to work properly

### ISSUE THREAD

**Issue by BobHogeveen** [DeepskyLog/DeepskyLog#655] opened 2017-03-28 12:59 UTC
Using RRO in a csv-file like this: RRO;STTA 74 AC;STTA;74 does not result in removing STTA 74 AC and attaching observations of to STTA 74.
First an errorpage is displayed and the objects are unchanged. Some time later both STTA 74 AC and STTA 74 are disappeared.... (in test environment!)

**Comment by WimDeMeester** [comment] 2017-03-31 13:53
The error message should indeed be fixed.

I'm trying to reproduce the error and I can see that the observation is indeed gone. However, I think that the problem is that there is no STTA 74 object yet. There is only an STT 74 object. I don't know if these objects are the same. First adding the STT 74 object and then executing RRO should not remove the observation...

**Comment by WimDeMeester** [comment] 2017-03-31 19:25
Fixed in DeepskyLog 5.0.51.

**Closed by WimDeMeester** 2017-03-31 19:25 UTC
Labels: bug, Deepsky, Deepsky database, in progress
