### ISSUE TITLE
Mobile display opens on regular PC using IE

### ISSUE THREAD

**Issue by TomCorstjens** [DeepskyLog/DeepskyLog#433] opened 2015-08-25 18:48 UTC
Experienced during Starnights, on several Windows7 computers, using IE: the mobile display opens instead of the regular PC display.
When using Firefox or Chrome, the problem did not happen.

**Comment by WimDeMeester** [comment] 2015-08-26 07:28
Do you know which version of Internet Explorer was used on these computers? 
+ Bootstrap, the underlying library does not work perfectly on very old versions of Internet Explorer (does not work at all on IE 7, starts to work on IE 8, but needs at least IE 9 to really work)...

Do you know the resolution of the screen of these computers?
+ If the resolution is too low, DeepskyLog (Bootstrap) will automatically switch to the mobile display.

**Comment by TomCorstjens** [comment] 2015-08-26 09:11
These are very modern computers, I did not check but it must be at least IE9 or newer. Screen resolution was VERY high, they even had touch screen interface. Extremely modern.

**Comment by WimDeMeester** [comment] 2015-08-26 09:17
Difficult to test without having access to the computers. This should not happen... Anyone who can reproduce this?

**Comment by rolfvandervleuten** [comment] 2015-08-27 10:49
to which version does this apply? and what is PC display / Mobile display

**Comment by WimDeMeester** [comment] 2015-08-27 11:01
It applies to the 5.0 version (the version in GitHub). The mobile display is this one: 

![mobile](https://cloud.githubusercontent.com/assets/7261529/9519007/94c88312-4cbb-11e5-9b59-db3d84dbe749.png)

While the PC display is normal version, like this one:

![newlook](https://cloud.githubusercontent.com/assets/7261529/9519042/beba7e32-4cbb-11e5-9dfd-41cdf55ba82c.png)

**Comment by rolfvandervleuten** [comment] 2015-08-27 11:12
tested on Win8 / IE 11. max width: 3000px. cannot reproduce. 
Will test on win 10.0 later

**Comment by WimDeMeester** [comment] 2015-10-09 19:47
I have seen this happen on IE8. IE9 works fine.

**Comment by WimDeMeester** [comment] 2015-10-29 11:21
I guess the compatibility mode on these PCs for Internet Explorer was set to IE 7 or so. This could explain why the mobile screen is displayed. I close this ticket, as we do not have access to the computers to test.

**Closed by WimDeMeester** 2015-10-29 11:21 UTC
Labels: bug
