### ISSUE TITLE
[Mac] Changing the number of rows shown in a search result does not persist.

### ISSUE THREAD

**Issue by svdwal** [DeepskyLog/DeepskyLog#699] opened 2018-02-26 19:05 UTC
- Execute a search
- When the result is displayed, select a higher number of rows to show, like 40
- Open an item
- The number of rows now returns to 10
- Set the number of rows to 40
- Close the item
- The number of rows becomes 10 again.

Personally, I would like this number to be a user setting, as I like working with big lists.

**Comment by WimDeMeester** [comment] 2018-02-27 09:41
This is a duplicate of #534.

**Comment by WimDeMeester** [comment] 2020-02-18 12:43
In the laravel version of DeepskyLog, the setting of the number of rows shown in tables is persistent. This ticket is difficult to solve in the current version of DeepskyLog. So I'm closing this ticket, because it will be fixed by the next major DeepskyLog release.

**Closed by WimDeMeester** 2020-02-18 12:43 UTC
Labels: DataTables, enhancement
