### ISSUE TITLE
Limit the creation of public observation lists

### ISSUE THREAD

**Issue by svdwal** [DeepskyLog/DeepskyLog#755] opened 2018-11-24 06:03 UTC
**Is your feature request related to a problem? Please describe.**
There are some people creating lots of weird public observation lists. One exampe is this one 
https://www.deepskylog.be/index.php?indexAction=listaction&activateList=true&listname=Herschel+objects+Scorpius

It is empty, given the name it is a list of William Herschel objects in a particular constellation. There are 88 constellations, I am not interested in lots of these lists, and given the way lists are interacted with, the use of other lists will be hugely impacted.

**Describe the solution you'd like**
This is more of a management than a coding issue, but there are some things that can be done in coding too.

1 empty lists, or very small ones, cannot be made public. Coding

2 Moderation. Every once in a while people look at the lists and remove the bad ones. There are some downsides to this: more time and mad people

3 moderation and coding: people can only create a few public lists. If they are creating good lists, they get a bigger budget

4 lots of coding: a more elaborate list management system that makes itbeasier to manage lots of lists

5 coding: you can unsubscribe from lists

**Comment by WimDeMeester** [comment] 2018-11-26 09:44
It is at number 2 on my list to rework the observing lists in DeepskyLog. All list will need a description in the future and you will only see the lists that you are subscribed to (so, a variant of your point 5).

The problem is that number 1 on my list will take a lot of time to implement and the I don't have a lot of time right now.

**Comment by svdwal** [comment] 2018-12-04 10:01
Ok. Maybe then a hint from the team to the list creators that some of their lists are clogging the list system, as it is now?

**Comment by WimDeMeester** [comment] 2020-02-19 18:48
In the laravel version of DeepskyLog, the observers need to subscribe to the lists they want to see (even to their own observing lists). All lists will have a description and it will be possible to 'like' lists. The more likes a list has, the higher it will appear in the page were the observer can subscribe to the lists.

**Comment by WimDeMeester** [comment] 2021-04-05 13:00
Will be fixed in the laravel version of DeepskyLog.

**Closed by WimDeMeester** 2021-04-05 13:00 UTC
Labels: Laravel, enhancement
